name: main
on:
  push:
  pull_request:

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.1

  test:
    name: test py39 - ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.9"
          miniforge-version: latest
      - name: install tox
        run: |
          mamba install tox
      - name: run test suite
        run: |
          PYVERSION="3.9"
          CONDA_EXE=mamba tox -- -m "not slow"
